name: Installing Python

on: 
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
  push:
    branches-ignore: 
      - feature/*     
      - test/**      
  pull_request:
    types:
      - opened
    paths-ignore:
      - requirements.txt

jobs:
  build:
    runs-on: ${{ matrix.os }}
    concurrency: 
      group: python-job
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        py-version: [3.7, 3.8, 3.9]
        exclude:
          - os: macos-latest
            py-version: 3.9

    steps:
    - name: Set up Python
      if: runner.os == 'Linux'
      timeout-minutes: 10
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.py-version }}